version: '2'

services:
  mongodb-user:
    image: mongo:latest
    container_name: "mongodb-user"
    network_mode: 'host'
    hostname: localhost
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    network_mode: 'host'
    hostname: localhost
    ports:
      - 15672:15672
      - 5672:5672

  mysql-user:
    container_name: "mysql-user"
    image: mysql:latest
    network_mode: 'host'
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    network_mode: 'host'
    hostname: localhost
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300