version: "2"

services:
  spring-cloud-gateway:
    build: spring-cloud-gateway/
    container_name: spring-cloud-gateway
    restart: always
    hostname: localhost
    ports:
      - 8080:8080

  registration-service:
    build: registration-service/
    container_name: registration-service
    restart: always
    hostname: localhost
    ports:
      - 8082:8082

  authentication-service:
    build: authenticationService/
    container_name: authentication-service
    restart: always
    hostname: localhost
    ports:
      - 8090:8090

  challenge-create-services:
    build: challenge-create-services/
    container_name: challenge-create-services
    restart: always
    hostname: localhost
    ports:
      - 8085:8085

  solution:
    build: Solution/
    container_name: solution
    restart: always
    hostname: localhost
    ports:
      - 8100:8100

  feedback-service:
    build: FeedbackService/
    container_name: feedback-service
    restart: always
    hostname: localhost
    ports:
      - 8070:8070

  search-service:
    build: searchService/
    container_name: search-service
    restart: always
    hostname: localhost
    ports:
      - 8105:8105

  webapp:
    build: ./webapp/
    container_name: webapp
    restart: always
    hostname: localhost
    ports:
      - 4200:4200